[project]
name = "radium226-pacman-repository"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "funcy>=2.0",
    "networkx>=3.4.2",
    "pydot>=3.0.4",
]

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "pytest>=8.3.4",
    "ruff>=0.8.6",
]

[tool.uv]
package = true
